In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

In [28]:
mul_pov = pd.read_excel("multidimensional_poverty.xlsx", skiprows=2)
mul_pov

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Monetary (%),Educational attainment (%),Educational enrollment (%),Electricity (%),Sanitation (%),Drinking water (%),Unnamed: 15
0,SSA,AGO,Angola,2018,IDREA,2018,N,c,2,31.122005,29.753423,27.44306,52.639532,53.637516,32.106507,47.203606
1,ECA,ALB,Albania,2012,HBS,2018,N,c,1,0.048107,0.19238,-,0.06025,6.579772,9.594966,0.293161
2,LAC,ARG,Argentina,2010,EPHC-S2,2021,U,i,3,0.894218,1.08532,0.731351,0,0.257453,0.364048,0.906573
3,ECA,ARM,Armenia,2010,ILCS,2021,N,c,1,0.523521,0,1.793004,0,0.397725,0.660082,0.523521
4,EAP,AUS,Australia,2010,SIH-LIS,2018,N,I,3,0.516880,1.71188,-,0,0,-,2.215770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,ECA,UZB,Uzbekistan,2022,HBS,2022,N,c,1,2.253092,0,-,0.12747,21.786885,10.693686,2.253092
106,EAP,VNM,Viet Nam,2010,VHLSS,2022,N,c,2,0.963795,3.384816,1.841407,0.079733,4.132901,1.968127,1.266184
107,EAP,VUT,Vanuatu,2010,NSDP,2019,N,c,0,9.963333,25.723079,13.404277,26.994166,42.970088,11.813611,19.892171
108,SSA,ZMB,Zambia,2010,LCMS-VIII,2022,N,c,4,64.341974,16.267821,23.39835,45.135146,53.505135,26.849246,66.506058
109,SSA,ZWE,Zimbabwe,2017,PICES,2019,N,c,0,39.754534,0.927006,5.984225,37.994787,38.285229,19.260145,42.397931

In [30]:
mul_pov.rename(columns={'Unnamed: 0':'Region', 'Unnamed: 1':'Country code',
                        'Unnamed: 2':'Economy', 'Unnamed: 3':'Reporting year',
                        'Unnamed: 4':'Survey name','Unnamed: 5':'Survey year',
                        'Unnamed: 6':'Survey coverage', 'Unnamed: 7':'Welfare type',
                        'Unnamed: 8':'Survey comparability', 'Unnamed: 15':'Multidimensional poverty headcount ratio (%)'},
              inplace=True)

In [31]:
mul_pov

,Region,Country code,Economy,Reporting year,Survey name,Survey year,Survey coverage,Welfare type,Survey comparability,Monetary (%),Educational attainment (%),Educational enrollment (%),Electricity (%),Sanitation (%),Drinking water (%),Multidimensional poverty headcount ratio (%)
0,SSA,AGO,Angola,2018,IDREA,2018,N,c,2,31.122005,29.753423,27.44306,52.639532,53.637516,32.106507,47.203606
1,ECA,ALB,Albania,2012,HBS,2018,N,c,1,0.048107,0.19238,-,0.06025,6.579772,9.594966,0.293161
2,LAC,ARG,Argentina,2010,EPHC-S2,2021,U,i,3,0.894218,1.08532,0.731351,0,0.257453,0.364048,0.906573
3,ECA,ARM,Armenia,2010,ILCS,2021,N,c,1,0.523521,0,1.793004,0,0.397725,0.660082,0.523521
4,EAP,AUS,Australia,2010,SIH-LIS,2018,N,I,3,0.516880,1.71188,-,0,0,-,2.215770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,ECA,UZB,Uzbekistan,2022,HBS,2022,N,c,1,2.253092,0,-,0.12747,21.786885,10.693686,2.253092
106,EAP,VNM,Viet Nam,2010,VHLSS,2022,N,c,2,0.963795,3.384816,1.841407,0.079733,4.132901,1.968127,1.266184
107,EAP,VUT,Vanuatu,2010,NSDP,2019,N,c,0,9.963333,25.723079,13.404277,26.994166,42.970088,11.813611,19.892171
108,SSA,ZMB,Zambia,2010,LCMS-VIII,2022,N,c,4,64.341974,16.267821,23.39835,45.135146,53.505135,26.849246,66.506058
109,SSA,ZWE,Zimbabwe,2017,PICES,2019,N,c,0,39.754534,0.927006,5.984225,37.994787,38.285229,19.260145,42.397931

In [32]:
mul_pov.replace("-", np.nan, inplace=True)

In [34]:
mul_pov = mul_pov.dropna()
mul_pov

,Region,Country code,Economy,Reporting year,Survey name,Survey year,Survey coverage,Welfare type,Survey comparability,Monetary (%),Educational attainment (%),Educational enrollment (%),Electricity (%),Sanitation (%),Drinking water (%),Multidimensional poverty headcount ratio (%)
0,SSA,AGO,Angola,2018,IDREA,2018,N,c,2,31.122005,29.753423,27.443060,52.639532,53.637516,32.106507,47.203606
2,LAC,ARG,Argentina,2010,EPHC-S2,2021,U,i,3,0.894218,1.085320,0.731351,0.000000,0.257453,0.364048,0.906573
3,ECA,ARM,Armenia,2010,ILCS,2021,N,c,1,0.523521,0.000000,1.793004,0.000000,0.397725,0.660082,0.523521
6,SSA,BDI,Burundi,2013,EICVMB,2020,N,c,1,62.065762,44.881231,34.211618,90.568537,91.007495,12.021417,79.209852
8,SSA,BEN,Benin,2015,EHCVM,2021,N,c,1,12.723279,49.023893,31.661823,34.818304,76.649594,24.109130,45.443240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,LAC,URY,Uruguay,2010,ECH-S2,2021,N,i,3,0.112155,1.855258,0.482043,0.028709,1.953975,0.593860,0.148147
106,EAP,VNM,Viet Nam,2010,VHLSS,2022,N,c,2,0.963795,3.384816,1.841407,0.079733,4.132901,1.968127,1.266184
107,EAP,VUT,Vanuatu,2010,NSDP,2019,N,c,0,9.963333,25.723079,13.404277,26.994166,42.970088,11.813611,19.892171
108,SSA,ZMB,Zambia,2010,LCMS-VIII,2022,N,c,4,64.341974,16.267821,23.398350,45.135146,53.505135,26.849246,66.506058
109,SSA,ZWE,Zimbabwe,2017,PICES,2019,N,c,0,39.754534,0.927006,5.984225,37.994787,38.285229,19.260145,42.397931

In [37]:
hiv_data = pd.read_csv("HIV data 2000-2023.csv", encoding='ISO-8859-1', thousands=' ')
hiv_data['Value'] = hiv_data['Value'].str.extract(r'(\d[\d\s]+)')[0].str.replace(' ', '').astype(float)
hiv_data

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,Value
0,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2023,320000.0
1,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2022,320000.0
2,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2021,320000.0
3,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,320000.0
4,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2015,300000.0
...,...,...,...,...,...,...,...,...,...,...,...
1547,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2020,NaN
1548,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2015,NaN
1549,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2010,NaN
1550,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2005,NaN
1551,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2000,NaN

In [38]:
hiv_data = hiv_data.dropna()
hiv_data

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,Value
0,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2023,320000.0
1,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2022,320000.0
2,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2021,320000.0
3,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,320000.0
4,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2015,300000.0
...,...,...,...,...,...,...,...,...,...,...,...
1531,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2020,250000.0
1532,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2015,240000.0
1533,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2010,210000.0
1534,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2005,180000.0
1535,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2000,120000.0

In [40]:
# Make sure Period and Reporting year are numeric
hiv_data['Period'] = pd.to_numeric(hiv_data['Period'])
mul_pov['Reporting year'] = pd.to_numeric(mul_pov['Reporting year'])

# Merge on Country Code and Year
merged_df = pd.merge(
    hiv_data,
    mul_pov,
    how='left',
    left_on=['SpatialDimValueCode', 'Period'],
    right_on=['Country code', 'Reporting year']
)

C:\Users\pc\AppData\Local\Temp\ipykernel_2440\279907246.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hiv_data['Period'] = pd.to_numeric(hiv_data['Period'])
C:\Users\pc\AppData\Local\Temp\ipykernel_2440\279907246.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mul_pov['Reporting year'] = pd.to_numeric(mul_pov['Reporting year'])

In [41]:
merged_df

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,Survey coverage,Welfare type,Survey comparability,Monetary (%),Educational attainment (%),Educational enrollment (%),Electricity (%),Sanitation (%),Drinking water (%),Multidimensional poverty headcount ratio (%)
0,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1155,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2010,...,N,c,2.0,0.963795,3.384816,1.841407,0.079733,4.132901,1.968127,1.266184
1156,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1157,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# Drop rows where 'Multidimensional poverty headcount ratio (%)' is missing
clean_df = merged_df.dropna(subset=["Multidimensional poverty headcount ratio (%)"]).reset_index(drop=True)

Shape after cleaning: (32, 27)
        Location  Period      Value  \
0          Benin    2015    71000.0
1  Cote d'Ivoire    2015   460000.0
2  Guinea-Bissau    2010    37000.0
3          Kenya    2015  1500000.0
4         Malawi    2010   930000.0

   Multidimensional poverty headcount ratio (%)
0                                     45.443240
1                                     29.177094
2                                     38.730049
3                                     38.490102
4                                     78.252000

In [47]:
# Correlation Check
correlation = clean_df['Value'].corr(clean_df['Multidimensional poverty headcount ratio (%)'])
print(f"Correlation between HIV and Poverty headcount: {correlation:.2f}")

Correlation between HIV and Poverty headcount: 0.73

In [49]:
clean_df = clean_df.rename(columns={
    "Monetary (%)": "monetary",
    "Educational attainment (%)": "educational_attainment",
    "Educational enrollment (%)": "educational_enrollment",
    "Electricity (%)": "electricity",
    "Sanitation (%)": "sanitation",
    "Drinking water (%)": "drinking_water",
    "Multidimensional poverty headcount ratio (%)": "poverty_headcount",
    "Value": "hiv_cases"
})

# Optional: Drop any rows that still have missing values in the predictors
model_df = clean_df.dropna(subset=[
    "poverty_headcount",
    "monetary",
    "educational_attainment",
    "educational_enrollment",
    "electricity",
    "sanitation",
    "drinking_water"
])

# Mixed Effects Model
expanded_model = smf.mixedlm(
    "hiv_cases ~ poverty_headcount + electricity + sanitation + drinking_water + educational_attainment + educational_enrollment + monetary",
    model_df,
    groups=model_df["Location"],
    re_formula="~Period"
)
expanded_result = expanded_model.fit()

# Show results
print(expanded_result.summary())

                        Mixed Linear Model Regression Results
======================================================================================
Model:                       MixedLM           Dependent Variable:           hiv_cases
No. Observations:            32                Method:                       REML
No. Groups:                  32                Scale:                        4383.8543
Min. group size:             1                 Log-Likelihood:               -344.1920
Max. group size:             1                 Converged:                    Yes
Mean group size:             1.0
--------------------------------------------------------------------------------------
                         Coef.         Std.Err.       z    P>|z|    [0.025     0.975]
--------------------------------------------------------------------------------------
Intercept              -26806.210         42829.006 -0.626 0.531 -110749.519 57137.100
poverty_headcount        4919.779         16357.700  0.301 0.764  -27140.724 36980.282
electricity            -10788.327          7118.022 -1.516 0.130  -24739.393  3162.740
sanitation              -4286.043          2673.395 -1.603 0.109   -9525.801   953.715
drinking_water          23580.660          6465.308  3.647 0.000   10908.890 36252.431
educational_attainment   8898.636          4892.427  1.819 0.069    -690.346 18487.618
educational_enrollment -16145.018          6405.824 -2.520 0.012  -28700.204 -3589.833
monetary                15872.690         10721.697  1.480 0.139   -5141.449 36886.830
Group Var                4383.854 6360864844621.497
Group x Period Cov          0.000    3165404533.971
Period Var               4383.854       1575236.492
======================================================================================

C:\Users\pc\anaconda3\lib\site-packages\statsmodels\regression\mixed_linear_model.py:2261: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)